[usuarios]

[usuarios."ayucra@apparka.pe"]
nombre   = "Abel Yucra"
password = "47609417"

[usuarios."azamudio@apparka.pe"]
nombre   = "Aldo Zamudio"
password = "43364757"

[usuarios."avega@apparka.pe"]
nombre   = "Alejandra Vega"
password = "70022351"

[usuarios."aroca@apparka.pe"]
nombre   = "Alejandro Roca"
password = "48530399"

[usuarios."azucca@apparka.pe"]
nombre   = "Alejandro Zucca"
password = "70874126"

[usuarios."ahuaman@apparka.pe"]
nombre   = "Alexander Huaman"
password = "41353982"

[usuarios."aleon@apparka.pe"]
nombre   = "Alfredo Leon"
password = "42320514"

[usuarios."avasquez@apparka.pe"]
nombre   = "Alfredo Vasquez"
password = "77910540"

[usuarios."asan@apparka.pe"]
nombre   = "Alicia San Martin"
password = "47109353"

[usuarios."acerron@apparka.pe"]
nombre   = "Andree Cerron"
password = "46409274"

[usuarios."aramos@apparka.pe"]
nombre   = "Angela Ramos"
password = "40938505"

[usuarios."asalvador@apparka.pe"]
nombre   = "Arnold Salvador"
password = "73357334"

[usuarios."aguardia@apparka.pe"]
nombre   = "Ayax Guardia"
password = "09906945"

[usuarios."bchavez@apparka.pe"]
nombre   = "Braulio Chavez"
password = "44730393"

[usuarios."bmagallanes@apparka.pe"]
nombre   = "Brenda Magallanes"
password = "42286206"

[usuarios."ccapristan@apparka.pe"]
nombre   = "Carmen Capristan"
password = "42318205"

[usuarios."ccedano@apparka.pe"]
nombre   = "Carol Cedano"
password = "43069971"

[usuarios."cchang@apparka.pe"]
nombre   = "Catherine Chang"
password = "42933662"

[usuarios."ccamacho@apparka.pe"]
nombre   = "Cynthia Camacho"
password = "41630434"

[usuarios."dgonzales@apparka.pe"]
nombre   = "Dennis Gonzales"
password = "44004689"

[usuarios."dinouye@apparka.pe"]
nombre   = "Diana Inouye"
password = "40390623"

[usuarios."druiz@apparka.pe"]
nombre   = "Diego Ruiz"
password = "72665835"

[usuarios."duriarte@apparka.pe"]
nombre   = "Diego Uriarte"
password = "40889781"

[usuarios."dvelasquez@apparka.pe"]
nombre   = "Diego Velásquez"
password = "46670475"

[usuarios."dperez@apparka.pe"]
nombre   = "Dorian Pérez"
password = "44038724"

[usuarios."dcuba@apparka.pe"]
nombre   = "Doris Cuba"
password = "41059650"

[usuarios."eaguirre@apparka.pe"]
nombre   = "Erick Aguirre"
password = "47083587"

[usuarios."epadilla@apparka.pe"]
nombre   = "Erick Padilla"
password = "76136364"

[usuarios."esialer@apparka.pe"]
nombre   = "Erli Sialer"
password = "41202303"

[usuarios."emaldonado@apparka.pe"]
nombre   = "Ernesto Maldonado"
password = "40067456"

[usuarios."econtreras@apparka.pe"]
nombre   = "Everth Contreras"
password = "43888506"

[usuarios."eyauri@apparka.pe"]
nombre   = "Evil Yauri"
password = "46200026"

[usuarios."fespinoza@apparka.pe"]
nombre   = "Fabiola Espinoza"
password = "48402325"

[usuarios."fgomez@apparka.pe"]
nombre   = "Fernando Gomez"
password = "08208079"

[usuarios."fcaicedo@apparka.pe"]
nombre   = "Flavio Caicedo"
password = "75330706"

[usuarios."fojeda@apparka.pe"]
nombre   = "Franco Ojeda"
password = "47282557"

[usuarios."ggutierrez@apparka.pe"]
nombre   = "Gabriela Gutierrez"
password = "40866318"

[usuarios."gnovoa@apparka.pe"]
nombre   = "Gaby Novoa"
password = "43675715"

[usuarios."gpena@apparka.pe"]
nombre   = "Gerson Peña"
password = "70835875"

[usuarios."gmora@apparka.pe"]
nombre   = "Gloria Mora"
password = "09302617"

[usuarios."htorres@apparka.pe"]
nombre   = "Harry Torres"
password = "10762812"

[usuarios."jpanez@apparka.pe"]
nombre   = "James Panez"
password = "72478131"

[usuarios."jcarlo@apparka.pe"]
nombre   = "Jean Carlo Albán"
password = "44017037"

[usuarios."jvilchez@apparka.pe"]
nombre   = "Jeffrey Vilchez"
password = "73609210"

[usuarios."jflores@apparka.pe"]
nombre   = "Jenny Flores"
password = "18198123"

[usuarios."jjeri@apparka.pe"]
nombre   = "John Jeri"
password = "10325498"

[usuarios."jcastaneda@apparka.pe"]
nombre   = "Jorge Castañeda"
password = "43551076"

[usuarios."jsenmache@apparka.pe"]
nombre   = "Jorge Senmache"
password = "44480604"

[usuarios."jllerena@apparka.pe"]
nombre   = "Jose Luis Llerena"
password = "07760153"

[usuarios."jarenas@apparka.pe"]
nombre   = "Joshua Arenas"
password = "70751253"

[usuarios."kluyo@apparka.pe"]
nombre   = "Kelly Luyo"
password = "45414983"

[usuarios."kalvarez@apparka.pe"]
nombre   = "Khristian Alvarez"
password = "72735191"

[usuarios."lcortegana@apparka.pe"]
nombre   = "Lennin Cortegana"
password = "70199357"

[usuarios."ltaype@apparka.pe"]
nombre   = "Lizeth Taype"
password = "75221160"

[usuarios."mestela@apparka.pe"]
nombre   = "Maria Estela Guillen"
password = "10346833"

[usuarios."mramos@apparka.pe"]
nombre   = "Marjhory Ramos"
password = "75716779"

[usuarios."mcarpio@apparka.pe"]
nombre   = "Marwin Carpio"
password = "42920033"

[usuarios."mcolan@apparka.pe"]
nombre   = "Mayra Colan"
password = "44789844"

[usuarios."mhuerta@apparka.pe"]
nombre   = "Mayra Huerta"
password = "46015110"

[usuarios."mchira@apparka.pe"]
nombre   = "Mayte Chira"
password = "71597005"

[usuarios."nmoreno@apparka.pe"]
nombre   = "Niel Moreno"
password = "43626860"

[usuarios."oaguirre@apparka.pe"]
nombre   = "Oswaldo Aguirre"
password = "45077315"

[usuarios."pespinoza@apparka.pe"]
nombre   = "Paul Espinoza"
password = "43943162"

[usuarios."raguirre@apparka.pe"]
nombre   = "Rafael Aguirre"
password = "41849484"

[usuarios."rchung@apparka.pe"]
nombre   = "Roberto Chung"
password = "47187986"

[usuarios."rrojas@apparka.pe"]
nombre   = "Rosario Rojas"
password = "10247869"

[usuarios."rapaza@apparka.pe"]
nombre   = "Ruben Apaza"
password = "70058438"

[usuarios."ssumary@apparka.pe"]
nombre   = "Sabrina Sumary"
password = "42821635"

[usuarios."smendoza@apparka.pe"]
nombre   = "Sheyla Mendoza"
password = "46596211"

[usuarios."vrubina@apparka.pe"]
nombre   = "Vanessa Rubina"
password = "41520409"

[usuarios."vsevillano@apparka.pe"]
nombre   = "Venus Sevillano"
password = "70368393"

[usuarios."vbenites@apparka.pe"]
nombre   = "Veronica Benites"
password = "46674113"

[usuarios."valarcon@apparka.pe"]
nombre   = "Victoria Alarcon"
password = "09903393"

[usuarios."wdalguer@apparka.pe"]
nombre   = "Walter Dalguer"
password = "43710410"

[usuarios."xquispe@apparka.pe"]
nombre   = "Xiomara Quispe"
password = "74372964"

[usuarios."oa@apparka.pe"]
nombre   = "RRHH Admin"
password = "Admin2026!"

